Convert this addon to v2 format
scalvert/ember-date-service pull request #174
Opened 2022-05-20 04:38 UTC by nlfurniss

## Summary
Converts this addont to addon v2 format by following [this guide](https://github.com/embroider-build/embroider/blob/main/PORTING-ADDONS-TO-V2.md).

Done in two commits
- Part 1: Separate Addon from Dummy App
- Addon V2

## Testing Done
`addon` builds and `ember test/serve/build` all work correctly and all tests pass

2022-05-20 04:43 UTC, nlfurniss commented
CI doesn't run for any PR; is it because [of this](https://github.com/ember-mocks/ember-date-service/blob/master/.github/workflows/ci-build.yml#L8)?

Should it be

```diff
-  pull_request: {}
+  pull_request:

```

2022-05-23 16:07 UTC, scalvert commented
> CI doesn't run for any PR; is it because [of this](https://github.com/ember-mocks/ember-date-service/blob/master/.github/workflows/ci-build.yml?rgh-link-date=2022-05-20T04%3A43%3A17Z#L8)?
> 
> Should it be?
> 
> ```diff
> -  pull_request: {}
> +  pull_request:
> ```

No, that should allow all PRs to run CI.

2022-05-23 16:30 UTC, scalvert commented
It looks like we're going to have to bump node along with this change. Likely to Node 14.

2022-05-23 18:18 UTC, nlfurniss commented on test-app/ember-cli-build.js
> +const EmberApp = require('ember-cli/lib/broccoli/ember-app');
Not sure how to fix this, as this dep is defined in the [test app's package.json](https://github.com/ember-mocks/ember-date-service/pull/174/files#diff-b03f4acb30e04ceb12a40763ef649759b3f632df2357bcec14fab6dd29ebbfb4R28), but doesn't get installed in the `test-app/node_modules`

2022-05-23 20:10 UTC, nlfurniss commented
All tests pass locally now:

```
All 7 scenarios succeeded
✨  Done in 278.00s.
```

2022-05-23 20:39 UTC, nlfurniss commented
Running `cd addon && yarn build`  adds this line to the the addon package.json file:

```json
    "app-js": {
      "./services/date.js": "./dist/_app_/services/date.js"
    }
```

Which is required for tests to pass locally, but seems to be why they're failing in CI

2022-05-23 21:07 UTC, scalvert commented
So any reason why we're not converting to a monorepo? This is the [recommended structure of v2 addons](https://github.com/embroider-build/embroider/blob/main/PORTING-ADDONS-TO-V2.md#monorepo-organization), and is what we used for ember-lifeline's conversion (which worked out really well).

2022-05-23 21:10 UTC, scalvert commented
Nevermind, I see you are following those instructions (which don't use `packages/*` as the defined workspaces).

2022-06-06 17:27 UTC, scalvert requested changes

2022-06-06 17:27 UTC, scalvert commented on .gitignore
> +.DS_Store
I think this should be in your global gitignore rather than the repo-specific one.

2022-06-06 17:27 UTC, scalvert commented on addon/.eslintrc.js
> +  parser: 'babel-eslint',
This parser is deprecated, so should probably be updated too. It's OK to do this in a separate PR.

2022-06-06 17:27 UTC, scalvert commented on addon/.gitignore
> +.DS_Store
Probably should be in your global gitignore.

2022-06-16 16:59 UTC, scalvert approved these changes

2022-06-16 16:59 UTC, scalvert commented on test-app/package.json
> +  },
We're never going to release this package, so probably don't need this release-it config?

2022-06-16 16:59 UTC, scalvert commented
Thank you so so so much @nlfurniss for doing this work. It's massively appreciated!

2022-06-16 18:08 UTC, merged